### PR TITLE
Document the xhtml option

### PR DESCRIPTION
**Pull request by gibson042**
Copied from https://github.com/chjj/marked/pull/944 .

### CODE REVIEW

**Comment by joshbruce** [comment]
@gibson042: I don't know the intricacies of this library well enough right now. If I'm understanding the PR correctly. This exposes the true/false setting for account for XHTML requirement of forward slashes for self-closing elements.

Does this also allow for - or just expose - the possibility of turning this feature on and off? Trying to figure out if we're adding a new feature to Marked that wasn't possible; or, just exposing a feature that was already there and *literally* just not documented.

**Comment by UziTech** [comment]
This was already a feature. This pull request is just documenting it with the other options.

LGTM

**Comment by joshbruce** [comment]
@UziTech: Just for my own edification to confirm - you have the ability to merge a PR, yeah?

**Comment by UziTech** [comment]
Ya I just didn't want to merge it if you saw something wrong with it since you were here first.

**Pull request merged**
